In [50]:
import os
import pandas as pd
from IPython.display import display, HTML

# Orca Plotter

+ Specify Molecule
+ Visualize Results

In [51]:
molecule = 'n2'
molecule_path = str()
subfolders = []

for item in os.listdir('.'):
    if molecule in item:
        molecule_path = os.path.join(os.getcwd(), item)

print(f"Path to the molecule '{molecule}': {molecule_path}")
# Loop over all subfolders
for item in os.listdir(molecule_path):
    subfolders.append(os.path.join(molecule_path, item))

print(f"Subfolders found: {subfolders}")

Path to the molecule 'n2': /home/lme/practical_course/practical_course_bachelor/n2
Subfolders found: ['/home/lme/practical_course/practical_course_bachelor/n2/b3lyp_6_311_g_dp', '/home/lme/practical_course/practical_course_bachelor/n2/mp2_6_311_g_dp', '/home/lme/practical_course/practical_course_bachelor/n2/hf_6_311_g_dp']

### Frequencies:

Workflow:

+ Open up all the subfolders
+ Open the `orca.out` file in each subfolder
+ Extract the frequencies from the `orca.out` file
+ Display them for comparison

In [52]:
# Search for the 'molecule.out' file in each subfolder

molecule_out_files = []
for subfolder in subfolders: 
    molecule_out_file = os.path.join(subfolder, molecule.lower() + '.out')
    molecule_out_files.append(molecule_out_file)

# Loop through all the files and open them
total_frequencies = []
for molecule_out_file in molecule_out_files:
    if os.path.exists(molecule_out_file):
        with open(molecule_out_file, 'r') as file:
            output = file.read()
            # Seach for VIBRATIONAL FREQUENCIES
            frequencies = pd.DataFrame(columns=['Mode', 'Frequency (cm-1)'])
            frequencies_block = []
            switch = False
            for line in output.splitlines():
                if 'VIBRATIONAL FREQUENCIES' in line:
                    switch = True

                if switch:
                    frequencies_block.append(line.strip())

                if 'NORMAL MODES' in line:
                    switch = False
            
            # Loop through the frequencies block and save the frequencies 
            for line in frequencies_block:
                # If line starts with number, it is a frequency line
                if line and line[0].isdigit():
                    parts = line.split()
                    mode = parts[0]
                    frequency_value = parts[1]
                    data = pd.DataFrame([[mode, frequency_value]], columns=['Mode', 'Frequency (cm-1)'])
                    frequencies = pd.concat([frequencies, data], ignore_index=True)

            total_frequencies.append(frequencies)
    
# Print all the frequencies with nice pandas formatting
            
for df in total_frequencies:
    display(df)

  Mode Frequency (cm-1)
0   0:             0.00
1   1:             0.00
2   2:             0.00
3   3:             0.00
4   4:             0.00
5   5:          2446.56

  Mode Frequency (cm-1)
0   0:             0.00
1   1:             0.00
2   2:             0.00
3   3:             0.00
4   4:             0.00
5   5:          2179.40

  Mode Frequency (cm-1)
0   0:             0.00
1   1:             0.00
2   2:             0.00
3   3:             0.00
4   4:             0.00
5   5:          2739.71